routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\VehicleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return view ('app');
});

Route::get("teszt", [TestController::class, 'teszt']);
Route::resource('users', UserController::class);
Route::get("login", [UserController::class, 'login'])->name('users.login');
Route::get("register", [UserController::class, 'register'])->name('users.register');
Route::resource('vehicles', VehicleController::class);

resources/views/app.blade.php
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/css/app.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.14.3/dist/css/uikit.min.css" />
    </head>

    <body>
    <div class="uk-background-secondary uk-light">
    <div class="uk-container">
    <nav class="uk-navbar-container uk-navbar-transparent" uk-navbar>
    <div class="uk-navbar-left">

        <ul class="uk-navbar-nav">
            <!--<li>
                <a href="#">Felhasználók</a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                    </ul>
                </div>
            </li>-->
            <li class=""><a href="{{ route('users.index') }}">Felhasználók</a></li>
            <!--<li>
                <a href="#">Járművek</a>
                <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">

                    </ul>
                </div>
            </li>-->
            <li class=""><a href="{{ route('vehicles.index') }}">Járművek</a></li>
            <li><a href="#">Item</a></li>
        </ul>

        </div>
    </nav>
    </div>
</div>
    <div id="app" class="uk-container">
        <div class="uk-card-body">
            @yield('content')
        </div>
    </div>
        <script src="https://cdn.jsdelivr.net/npm/uikit@3.14.3/dist/js/uikit.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/uikit@3.14.3/dist/js/uikit-icons.min.js"></script>
        <script src="/js/app.js"></script>
    </body>
</html>

resources/views/login.blade.php
@extends('app')
@section('content')
<form method="post" action="{{ route('postlogin') }}">
    <div class="uk-card uk-width-1-3@m uk-align-center uk-card-small uk-card-default">
        <div class="uk-card-head">
            <h3 class="uk-text-center">Bejelentkezés</h3>
        </div>
        <div class="uk-card-body">
                <div class="uk-child-width-1-1@m">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: user"></span>
                        <input name="email" id="email" type="email" class="uk-input uk-input-small uk-form-small" />
                    </div>
                    <div class="uk-inline uk-margin-medium-top">
                        <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
                        <input name="password" id="password" type="password" class="uk-input uk-input-small uk-form-small" />
                    </div>
                </div>
                <div class="uk-margin-medium-top">
                    <button type="submit" class="uk-button uk-button-primary uk-width-1-1@m">Bejelentkezés</button>
                </div>
        </div>
    </div>
</form>
@endsection

resources/views/register.blade.php
@extends('app')
@section('content')
<form method="post" action="{{ route('postregister') }}">
    <div class="uk-card-body uk-card uk-card-default">
        <div uk-grid class="uk-grid-small uk-child-width-1-2@m">
            <div>
                <label for="last_name">Vezetéknév
                    <input name="last_name" id="last_name" type="text" class="uk-input" />
                </label>
            </div>
            <div>
                <label for="first_name">Keresztnév
                    <input name="first_name" id="first_name" type="text" class="uk-input" />
                </label>
            </div>
            <div class="uk-width-1-1@m">
                <label for="email">Email
                    <input name="email" id="email" type="email" class="uk-input" />
                </label>
            </div>
            <div>
                <label for="password">Jelszó
                    <input name="password" id="password" type="password" class="uk-input" />
                </label>
            </div>
            <div>
                <label for="confirm_password">Jelszó mégegyszer
                    <input name="confirm_password" id="confirm_password" type="password" class="uk-input" />
                </label>
            </div>  
        </div>
        <button class="uk-button uk-button-primary uk-margin-small-top uk-width-1-1@m" type="submit">Küldés</button>
    </div>
</form>
@endsection

resources/views/teszt.blade.php
<html>
<strong>Database Connected: </strong>
<?php
     try {

        DB::Connection()->getPdo();
        } catch (PDOException $e) {

            echo $e->getMessage();
        }
    ?>
    <body>
        <h1>{{$count}} darab</h1>
        <table>
            <thead>
                <tr>
                    @for ($i = 1; $i <= count($metszet); $i++)
                        <th>{{$i}}</th>
                    @endfor
                </tr>
            </thead>
            <tbody>
                <tr>
                    @foreach($metszet as $number)
                        <td>{{$number}}</td>
                    @endforeach
                </tr>
            </tbody>
        </table>
    </body>
</html>

resources/views/user_edit.blade.php
@extends('app')
@section('content')
<form class="uk-form-stacked" action="{{ url('/users/'.$id) }}" method="POST">
    @csrf
    @method('PUT')
    <label for="last_name">Vezetéknév
        <input class="uk-input" value="{{$user->last_name}}" name="last_name" id="last_name" />
    </label>
    <label for="first_name">Keresztnév
        <input class="uk-input" value="{{$user->first_name}}" name="first_name" id="first_name" />
    </label>
    <label for="email">E-mail
        <input class="uk-input" value="{{$user->email}}" name="email" id="email" />
    </label>
    <button class="uk-button uk-button-primary" type="submit">Küldés</button>
</form>
<h2>Hozzá tartozó járművek:</h2>
<div uk-grid class="uk-grid-small uk-child-width-1-3@m">
    @foreach($owned_vehicles as $v)
    <div class="uk-card uk-card-default">
        <div class="uk-card-body">
            {{$v->plate_number}}
        </div>
    </div>
    @endforeach
</div>
@endsection

resources/views/users.blade.php
@extends('app')
@section('content')
<div class="uk-grid-small" uk-grid>
    <div><a href="{{route('users.login')}}" class="uk-button uk-button-primary">Bejelentkezés</a></div>
    <div><a href="{{route('users.register')}}" class="uk-button uk-button-primary">Regisztráció</a></div>
</div>
<table class="uk-table uk-table-hover uk-table-striped">
    <thead>
        <tr>
            <th>Vezetéknéb</th>
            <th>Keresztnév</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->first_name}}</td>
            <td>{{$user->last_name}}</td>
            <td>{{$user->email}}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/users_create.blade.php
@extends('app')
@section('content')
<form class="uk-form-stacked" action="{{route('users.store')}}" method="POST">
    @csrf
    <label for="last_name">Vezetéknév
        <input class="uk-input" name="last_name" id="last_name" />
    </label>
    <label for="first_name">Keresztnév
        <input class="uk-input" name="first_name" id="first_name" />
    </label>
    <label for="email">E-mail
        <input class="uk-input" name="email" id="email" />
    </label>
    <button class="uk-button uk-button-primary" type="submit">Küldés</button>
</form>
@endsection

resources/views/vehicle_edit.blade.php
@extends('app')
@section('content')
<form class="uk-form-stacked" action="{{ route('vehicles.update', ['vehicle' => $vehicle->id]) }}" method="post">
    @csrf
    @method('PUT')
    <label for="plate_number">Rendszám:
        <input class="uk-input" name="plate_number" id="plate_number" value="{{$vehicle->plate_number}}" />
    </label>
    <label for="owner">Tulajdonos
        <select name="owner_id" id="owner" class="uk-select" value="{{$vehicle->owner_id}}">
                <option disabled>Jelenlegi tulajdonos: {{$vehicle->owner_id}} sorszámú személy</option>
            @foreach($users as $user)
                <option name="owner_id" value="{{$user->id}}">{{'Sorszám: '.$user->id.' Teljesnév:'.$user->last_name.' '.$user->first_name}}</option>
            @endforeach
        </select>
    </label>
    <button class="uk-button uk-button-primary" type="submit">Küldés</button>
</form>
<h2>Jelenlegi tulajdonos:</h2>
<div class="uk-text-muted">{{$owner->last_name.' '. $owner->first_name}}</div>
@endsection

resources/views/vehicles.blade.php
@extends('app')
@section('content')
<h1>Vehicle View</h1>
<table class="uk-table uk-table-striped uk-table-responsive uk-table-small uk-table-hover">
        <caption class="uk-text-lead">Járművek listája</caption>
        <thead>
            <tr>
                <th>Rendszám</th>
                <th>Tulajdonos</th>
                <th>Szerkesztés</th>
            </tr>
        </thead>
        <tbody>
            @foreach($vehicles as $v)
                <tr>
                    <td>{{$v->plate_number}}</td>
                    <td>{{$v->owner_id}}</td>
                    <td><a class="uk-button uk-button-primary uk-button-small" href="{{ route('vehicles.edit', ['vehicle' => $v->id]) }}">Szerkesztés</a></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{$vehicles}}
@endsection